<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
        <?= $this->headStyle() ?>
        <base href="/" />
    </head>
    <body>
        <div class="container">
        	<div id="header">
                <h1>Aggregator <span class="green">Alligator</span></h1> 
            </div>
        	<div class="content">
        		<div id="mainbar">
                <?= $this->layout()->content; ?>
                </div>
        		<div id="sidebar"></div>
        	</div>
        </div>
        <div id="footer">

        </div>
    </body>
</html>
