<div id="subheader">
    <div id="menu">
        <a href="#" class="active">Naujausi</a>
        <a href="#">Populiariausi</a>
        <a href="#">Aktualiausi</a>
    </div>
</div>
<div class="post">
    <div class="summary">
        <h3><a href="#">Ar verta naudoti Linux?</a></h3>
        <div class="meta">
            <a href="#">Pawka</a>
            <span class="date">2010 lapkričio 15</span>
        </div>
    </div>
</div>

<div class="post">
    <div class="summary">
        <h3><a href="#">Ar verta naudoti Linux?</a></h3>
        <div class="meta">
            <a href="#">Pawka</a>
            <span class="date">2010 lapkričio 15</span>
        </div>
    </div>
</div>

<div class="post">
    <div class="summary">
        <h3><a href="#">Ar verta naudoti Linux?</a></h3>
        <div class="meta">
            <a href="#">Pawka</a>
            <span class="date">2010 lapkričio 15</span>
        </div>
    </div>
</div>
