<?= $this->doctype() ?>
<html>
    <head>
        <base href="<?= $this->baseUrl() ?>/" />
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
        <?= $this->headStyle() ?>
        <style>

            a:link,
            a:visited
            {
                color: #0398CA;
            }

            span#zf-name
            {
                color: #91BE3F;
            }

        </style>
    </head>
<body>
<center>
    <div id="welcome">
        <br />
        <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>
        <h3>This is your project's main page</h3><br /><br />
        <div id="more-information">
            <a href="cron/fetch/">Fetch feeds</a> 
        </div>
    </div>
</center>
</body>
</html>
