<div id="subheader">
    <div id="menu">
        <a href="#" class="active">Naujausi</a>
        <a href="#">Populiariausi</a>
        <a href="#">Aktualiausi</a>
    </div>
</div>

<?php foreach ($this->list as $row) : ?>
<div class="post">
    <div class="summary">
        <h3><a href="<?=$row['link']?>" target="_blank"><?=$this->escape($row['title']);?></a></h3>
        <div class="meta">
            <a href="#">Pawka</a>
            <span class="date"><?=$row['date']?></span>
        </div>
    </div>
</div>
<?php endforeach; ?>
