<?php

/**
 * App_Model_Base_Wordlocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $post_id
 * @property integer $word_id
 * @property integer $location
 * @property App_Model_Posts $Posts
 * @property App_Model_Wordlist $Wordlist
 * 
 * @package    Aggregator
 * @subpackage Models
 * @author     Povilas Balzaravičius <pavvka@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class App_Model_Base_Wordlocation extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('wordlocation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('post_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('word_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('location', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('App_Model_Posts as Posts', array(
             'local' => 'post_id',
             'foreign' => 'id'));

        $this->hasOne('App_Model_Wordlist as Wordlist', array(
             'local' => 'word_id',
             'foreign' => 'id'));
    }
}