<?php

/**
 * App_Model_Base_Wordlist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $word
 * @property integer $weigth
 * @property Doctrine_Collection $Wordlocation
 * 
 * @package    Aggregator
 * @subpackage Models
 * @author     Povilas Balzaravičius <pavvka@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class App_Model_Base_Wordlist extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('wordlist');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('word', 'string', 127, array(
             'type' => 'string',
             'length' => 127,
             'fixed' => true,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('weigth', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('App_Model_Wordlocation as Wordlocation', array(
             'local' => 'id',
             'foreign' => 'word_id'));
    }
}