<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->

<?php if ($this->pageCount): ?>
<div class="paginationControl">
    <strong><?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?></strong>
    iš <strong><?php echo $this->totalItemCount; ?></strong>

    <!-- First page link -->
    <?php if (isset($this->previous)): ?>
    <a href="<?php echo $this->url(array('page' => $this->first)); ?>">&lt;&lt;</a>
    <?php endif; ?>

    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
    <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt;</a>
    <?php endif; ?>

    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
        <?php else: ?>
            <span class="disabled"><?php echo $page; ?></span>
        <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
    <a href="<?php echo $this->url(array('page' => $this->next)); ?>">&gt;</a>
    <?php endif; ?>

    <!-- Last page link -->
    <?php if (isset($this->next)): ?>
    <a href="<?php echo $this->url(array('page' => $this->last)); ?>">&gt;&gt;</a>
    <?php endif; ?>
</div>
<?php endif; ?>