<?php

/**
 * App_Model_FeedsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class App_Model_FeedsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object App_Model_FeedsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('App_Model_Feeds');
    }
}