<?php

/**
 * App_Model_Wordlist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Aggregator
 * @subpackage Models
 * @author     Povilas Balzaravičius <pavvka@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class App_Model_Wordlist extends App_Model_Base_Wordlist
{

}