<h2>Automobilių sąrašas</h2><br />


<div class="tablenav">
    <div>
        Puslapis: <?= $this->paginator; ?>
    </div>
</div>
<br class="clear" />
<table class="widefat">
    <thead>
        <tr>
            <th>ID</th>
            <th>Maker</th>
            <th>Model</th>
            <th>Years</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    <?php if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $item): ?>
        <tr>
            <td>#<?= $this->escape($item['id']) ?></td>
            <td><?= $this->escape($item['maker_name']) ?></td>
            <td><?= $this->escape($item['model_name']) ?></td>
            <td><?= $this->escape($item['year']) ?></td>
            <td>
                <a href="cars/edit/id/<?=$item['id']?>/">edit</a>,
                <a href="cars/delete/id/<?=$item['id']?>/">delete</a>
            </td>
        </tr>
        <?php endforeach; ?>
    <?php endif; ?>
    </tbody>
</table>
